; Supports both decimal and hexadecimal (prefixed with "0x").
; Prefix with "*" for pointer references.
; Group multiple blocks using [BEGIN][XXXX] and [END][XXXX].

[BEGIN][DEFAULT]

; Free space finder
FreeSpaceFinderOffset = 0x800000
FreeSpaceByteAmount = 2048








; Class Name
ClassNameTableOffset = *0xD80A0
ClassNameEntryLength = 0xD
ClassNameCount = 107
; Prize Multi
ClassPrizeMultiTableOffset = *0x259CC
ClassPrizeMultiplierCount = 105
; Extra Data
EnableClassEncounterMusic = false
ClassEncounterMusicTableOffset = ; gClassBasedTrainerEncounterBGM
EnableClassBattleMusic = false
ClassBattleMusicTableOffset = ; gClassBasedBattleBGM
EnableClassPokeBall = false
ClassPokeBallTableOffset = ; gClassPokeBalls
EnablesClassBaseIV = false
ClassBaseIVTableOffset = ; gBaseIVsByTrainerClass

[END][DEFAULT]
