; Supports both decimal and hexadecimal (prefixed with "0x").
; Prefix with "*" for pointer references.
; Prefix with "$" to search a byte pattern and read the trailing pointer.
; Append ", [number]" after the byte pattern to add an offset.
; Group multiple blocks using [BEGIN][XXXX] and [END][XXXX].

[BEGIN][DEFAULT]

; Free space finder
FreeSpaceFinderOffset = 0x800000
FreeSpaceByteAmount = 2048

[END][DEFAULT]
