; Supports both decimal and hexadecimal (prefixed with "0x").
; Prefix with "*" for pointer references.
; Replace [; gXXXX] after CFRU and DPE are installed.

; Free space finder
FreeSpaceFinderOffset = 0x800000
FreeSpaceByteAmount = 2048




; OverworldSprite
OverworldSpriteTableOffset = *0x5F2F4
OverworldSpritePaletteTableOffset = *0x5F4D8
; Unused?
OverworldSpriteLastIndex = 0x5F2E0
; Multiple
EnableMultipleOverworldSpriteTable = false
MultipleOverworldSpriteTableOffset = ; gOverworldTableSwitcher



; Class Name
ClassNameTableOffset = *0xD80A0
ClassNameEntryLength = 0xD
ClassNameCount = 107
; Prize Multi
ClassPrizeMultiTableOffset = *0x259CC
ClassPrizeMultiCount = 105
; Extra Data
EnableClassEncounterMusic = false
ClassEncounterMusicTableOffset = ; gClassBasedTrainerEncounterBGM
EnableClassBattleMusic = false
ClassBattleMusicTableOffset = ; gClassBasedBattleBGM
EnableClassPokeBall = false
ClassPokeBallTableOffset = ; gClassPokeBalls
EnableClassBaseIV = false
ClassBaseIVTableOffset = ; gBaseIVsByTrainerClass

; Trainer Sprite
TrainerImageTableOffset = *0x3473C
TrainerPaletteTableOffset = *0x3474C
TrainerYPositionTableOffset = *0x37E78
TrainerAnimPointerTableOffset = *0x3F8F4
TrainerSpriteCount = 148
